### ISSUE TITLE
Remove published pact contract on the pact broker

### ISSUE THREAD

**Issue by lifeifei** [bethesque/pact_broker-client#3]
Hi,

We've published some testing pact contracts on the broker when we building the pact broker.  Now we would like to remove these testing contracts from the broker. 

I had a look at the source code, the pact broker client/participants class only has patch/get methods to support list and publish pact contracts.  Do we have rake task to remove the contracts? 

Thanks,

Lifei

**Comment by dziemid** [comment]
Hi @bethesque 

What's the recommended approach to removing a pact, if I don't won't to delete the consumer and provider (as they may have some other pacts with other components)

Greg

**Comment by bethesque** [comment]
One pact version, or all the versions?

**Comment by dziemid** [comment]
All versions

**Comment by bethesque** [comment]
There isn't a single URL unfortunately. Did I implement /versions? You'll have to iterate through all the version URLs (or delete them from the database).

**Comment by dziemid** [comment]
Cool, thank you for clarification @bethesque :-)

I've actually ended up following initial suggestion (delete consumer) and republishing the pacts.

**Comment by jolinteohyh** [comment]
hi @bethesque , i'm actually looking for how to remove the version from the pact broker. for example i have 2 version in pact broker which is 111.111.111 and 222.222.222. and i would like to remove the 111.111.111 version.

**Comment by bethesque** [comment]
Do you mean delete a pact version or pacticipant version? For both of these resources, send a DELETE request to the resource (you'll need pact_broker v2.0.1 or later to access the DELETE pacticipant version endpoint).

For example

    curl -XDELETE http://broker/pacts/provider/PROVIDER/consumer/CONSUMER/version/111.111.111

**Comment by jolinteohyh** [comment]
@bethesque it works!!! thanks

**Comment by JimmyLv** [comment]
@bethesque Should we put the delete functionality in documentation or REAMDE?

**Comment by bethesque** [comment]
The API documentation is here: https://github.com/pact-foundation/pact_broker/wiki/API-documentation

It is missing a page for the pacticipant version however. You can raise an issue in the pact_broker repo if you like.

**Comment by yuranos** [comment]
Cleanup functionality would definitely be handy.

**Comment by bethesque** [comment]
You can delete any resource by sending a DELETE request to it through the API Browser https://github.com/pact-foundation/pact_broker/wiki/Deleting-resources

**Comment by JoeBmc** [comment]
How to remove a tag associated with a pact version. We have a pact initially created with a tag - build. Once deployed me mark it with tag- master. I thought that the tag will be replace with the latest tag. But what I see is, we have both the tags for this particular version which is kind of right. Is there a way to remove the tag - build.

**Comment by TAGC** [comment]
I tried sending a DELETE request to `https://mycompany.pact.dius.com.au/pacts/provider/<Provider>/consumer/<Consumer>/version/1.0.0.0` and got a 404 response.

There's content available at `.../versions` but nothing at `.../version/...`.

**Comment by TAGC** [comment]
Turns out it should be `https://broker/pacticipants/PROVIDER/versions/VERSION`.

**Comment by bethesque** [comment]
@TAGC `https://broker/pacticipants/PROVIDER/versions/VERSION` is the pacticipant (application) version resource, not the pact resource. To delete a pact, you do send a delete to the same URL that you use to publish it, so `DELETE https://mycompany.pact.dius.com.au/pacts/provider/<Provider>/consumer/<Consumer>/version/1.0.0.0` should work. If you can reproduce the issue, please let me know.

**Comment by TAGC** [comment]
@bethesque Ah okay, my bad. The thing I tried did what I wanted to do, so I think I was just getting my terminology confused.
