### ISSUE TITLE
Basic auth not working in latest tag (0.0.6)

### ISSUE THREAD

**Issue by Hatlen** [bethesque/pact_broker-client#5]
The version that's published to rubygems doesn't support basic_auth when publishing, the way it's documented in the README.md (HEAD).
If I run the gem from the HEAD at github it works fine (retries also seems to be implemented #2).
Would it be possible to publish a new version? 
Or is there any particular reason why it's not published? (more than lack of time)

I really enjoy working with this whole pact suite of gems, and the pact wiki is has lots of great info on microservices, thank you very much for an awesome job!

**Comment by bethesque** [comment]
A very good point! I do not know why it wasn't released. I've just done it now (version 1.0.0, I think we can consider it out of beta!).

**Comment by Hatlen** [comment]
Awesome! :+1:
